name: stea
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  font_awesome_flutter: ^9.1.0
  firebase_core:
  firebase_storage:
  firebase_analytics:
  image_picker:
  permission_handler:
  flutter_screenutil: ^5.0.0+2






  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  carousel_slider: ^1.3.0
  firebase_auth: ^1.4.1
  http: ^0.13.4
  scoped_model: ^1.1.0
  flutter_spinkit: ^5.1.0
  cloud_firestore: ^0.12.9+4
  animated_bottom_navigation_bar: ^0.3.2
  provider: ^6.0.2
  file_picker: ^4.3.3
#  path: ^1.8.0
#  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
     - images/


  fonts:
      - family: GoogleSans
        fonts:
         - asset: fonts/GoogleSansDisplay-Regular-v1.27.ttf
           
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

